### ISSUE TITLE
Issue in Angular 10 project

### ISSUE THREAD

**Issue by potula140798** [qligier/angular4-events#9]
Hi,

I have upgraded my angular project to version 10, where we are using angular4-events in our project. So, while upgrading to version 10, the below error is seen during compilation. Please help me out in resolving that.

ERROR in node_modules/angular4-events/esm/src/angular4-events.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders' requires 1 type argument(s).

3 static forRoot(): ModuleWithProviders;
~~~~~~~~~~~~~~~~~~~

Thanks,
Vivek

**Comment by qligier** [comment]
Hi Vivek,
I've released v10.0.0 that should be compatible with Angular 10. I hope this will solve your issue.
Kind regards,
Quentin

**Comment by potula140798** [comment]
Hi Quentin,
Yes, the issue got fixed after upgrading the version to v10.0.0. 
Thank you.
